#
# Makefile for the FreeHep JNI library
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.5 2003/06/30 22:50:25 duns Exp $
#

#
# User Configuration: Define targets
#
OBJS = JNICUtil JNIUtil
LIBS = FHJNI
DLLS = FHJNI
EXE =

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
