#
# Makefile for the AIDA-CONFIG utility
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.1 2003/10/13 18:37:03 duns Exp $
#

#
# User Configuration: Define targets
#
OBJS  = aida-config
LIBS = aida-config
DLLS = aida-config
EXE = aida-config
TEST =
LINKNOJAVA = true

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
