#
# Makefile for the VectorGraphics package
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.3 2003/12/09 01:15:57 duns Exp $
#

#
# User Configuration: Define targets
#
DEBUG = false

DVERSION= 1.2.2
DIRNAME = VectorGraphics-$(DVERSION)
DNAME = VectorGraphics-$(DVERSION)$(TAREXT)
DDIR  = ../../../LICENSE.txt
DDIR += ../../../LGPL.txt
DDIR += VectorGraphics.txt
DDIR += ../../../web/freehep/vectorgraphics/ReleaseNotes-$(DVERSION).xhtml
DLIB  = ../../../lib/freehep-graphicsio-*.jar \
        ../../../lib/freehep-graphicsio.jar \
        ../../../lib/freehep-graphics2d.jar \
        ../../../lib/freehep-base.jar
DEXAMPLES = test/ExportDialogExample.java

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
