/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CAIDRef */

#ifndef _Included_hep_aida_jni_CAIDRef
#define _Included_hep_aida_jni_CAIDRef
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
