/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CICloud2D */

#ifndef _Included_hep_aida_jni_CICloud2D
#define _Included_hep_aida_jni_CICloud2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    fill
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud2D_fill__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    fill
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud2D_fill__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    lowerEdgeX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_lowerEdgeX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    lowerEdgeY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_lowerEdgeY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    upperEdgeX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_upperEdgeX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    upperEdgeY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_upperEdgeY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    valueX
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_valueX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    valueY
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_valueY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    weight
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_weight
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    meanX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_meanX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    meanY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_meanY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    rmsX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_rmsX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    rmsY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud2D_rmsY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    convert
 * Signature: (IDDIDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud2D_convert__IDDIDD
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    convert
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud2D_convert___3D_3D
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    histogram
 * Signature: ()Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CICloud2D_histogram
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud2D
 * Method:    fillHistogram
 * Signature: (Lhep/aida/IHistogram2D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud2D_fillHistogram
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
