/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIAxis */

#ifndef _Included_hep_aida_jni_CIAxis
#define _Included_hep_aida_jni_CIAxis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    isFixedBinning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIAxis_isFixedBinning
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    lowerEdge
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIAxis_lowerEdge
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    upperEdge
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIAxis_upperEdge
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    bins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIAxis_bins
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    binLowerEdge
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIAxis_binLowerEdge
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    binUpperEdge
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIAxis_binUpperEdge
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    binWidth
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIAxis_binWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIAxis
 * Method:    coordToIndex
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIAxis_coordToIndex
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
