/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIHistogram3D */

#ifndef _Included_hep_aida_jni_CIHistogram3D
#define _Included_hep_aida_jni_CIHistogram3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    fill
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram3D_fill__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    fill
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram3D_fill__DDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binMeanX
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binMeanX
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binMeanY
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binMeanY
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binMeanZ
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binMeanZ
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binEntries
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_binEntries
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binEntriesX
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_binEntriesX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binEntriesY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_binEntriesY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binEntriesZ
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_binEntriesZ
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binHeight
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binHeight
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binHeightX
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binHeightX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binHeightY
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binHeightY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binHeightZ
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binHeightZ
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    binError
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_binError
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    meanX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_meanX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    meanY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_meanY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    meanZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_meanZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    rmsX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_rmsX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    rmsY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_rmsY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    rmsZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram3D_rmsZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    xAxis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogram3D_xAxis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    yAxis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogram3D_yAxis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    zAxis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogram3D_zAxis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    coordToIndexX
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_coordToIndexX
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    coordToIndexY
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_coordToIndexY
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    coordToIndexZ
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram3D_coordToIndexZ
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram3D
 * Method:    add
 * Signature: (Lhep/aida/IHistogram3D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram3D_add
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
