/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIProfile */

#ifndef _Included_hep_aida_jni_CIProfile
#define _Included_hep_aida_jni_CIProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    allEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile_allEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    extraEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile_extraEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    sumBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile_sumBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    sumAllBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile_sumAllBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    sumExtraBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile_sumExtraBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    minBinHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile_minBinHeight
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile
 * Method:    maxBinHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile_maxBinHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
