/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIAnalysisFactory */

#ifndef _Included_hep_aida_jni_CIAnalysisFactory
#define _Included_hep_aida_jni_CIAnalysisFactory
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024hep_00024aida_00024IAnalysisFactory */
/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    create
 * Signature: ()Lhep/aida/IAnalysisFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_create
  (JNIEnv *, jclass);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createTreeFactory
 * Signature: ()Lhep/aida/ITreeFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createTreeFactory
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createHistogramFactory
 * Signature: (Lhep/aida/ITree;)Lhep/aida/IHistogramFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createHistogramFactory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createDataPointSetFactory
 * Signature: (Lhep/aida/ITree;)Lhep/aida/IDataPointSetFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createDataPointSetFactory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createTupleFactory
 * Signature: (Lhep/aida/ITree;)Lhep/aida/ITupleFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createTupleFactory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createFunctionFactory
 * Signature: (Lhep/aida/ITree;)Lhep/aida/IFunctionFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createFunctionFactory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createPlotterFactory
 * Signature: ()Lhep/aida/IPlotterFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createPlotterFactory
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAnalysisFactory
 * Method:    createFitFactory
 * Signature: ()Lhep/aida/IFitFactory;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAnalysisFactory_createFitFactory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
