/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIAxisStyle */

#ifndef _Included_hep_aida_jni_CIAxisStyle
#define _Included_hep_aida_jni_CIAxisStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    lineStyle
 * Signature: ()Lhep/aida/ILineStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAxisStyle_lineStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    tickLabelStyle
 * Signature: ()Lhep/aida/ITextStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAxisStyle_tickLabelStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    labelStyle
 * Signature: ()Lhep/aida/ITextStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIAxisStyle_labelStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    setlineStyle
 * Signature: (Lhep/aida/ILineStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIAxisStyle_setlineStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    setTickLabelStyle
 * Signature: (Lhep/aida/ITextStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIAxisStyle_setTickLabelStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    setLabelStyle
 * Signature: (Lhep/aida/ITextStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIAxisStyle_setLabelStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIAxisStyle
 * Method:    setLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIAxisStyle_setLabel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
