/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIBaseHistogram */

#ifndef _Included_hep_aida_jni_CIBaseHistogram
#define _Included_hep_aida_jni_CIBaseHistogram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIBaseHistogram_title
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIBaseHistogram_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    annotation
 * Signature: ()Lhep/aida/IAnnotation;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIBaseHistogram_annotation
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    dimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIBaseHistogram_dimension
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIBaseHistogram_reset
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseHistogram
 * Method:    entries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIBaseHistogram_entries
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
