/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIBaseStyle */

#ifndef _Included_hep_aida_jni_CIBaseStyle
#define _Included_hep_aida_jni_CIBaseStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIBaseStyle_reset
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    setParameter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIBaseStyle_setParameter__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    setParameter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIBaseStyle_setParameter__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    parameterValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIBaseStyle_parameterValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    availableParameters
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIBaseStyle_availableParameters
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIBaseStyle
 * Method:    availableParameterOptions
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIBaseStyle_availableParameterOptions
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
