/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CICloud3D */

#ifndef _Included_hep_aida_jni_CICloud3D
#define _Included_hep_aida_jni_CICloud3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    fill
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud3D_fill__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    fill
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud3D_fill__DDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    lowerEdgeX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_lowerEdgeX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    lowerEdgeY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_lowerEdgeY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    lowerEdgeZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_lowerEdgeZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    upperEdgeX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_upperEdgeX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    upperEdgeY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_upperEdgeY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    upperEdgeZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_upperEdgeZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    valueX
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_valueX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    valueY
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_valueY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    valueZ
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_valueZ
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    weight
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_weight
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    meanX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_meanX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    meanY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_meanY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    meanZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_meanZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    rmsX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_rmsX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    rmsY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_rmsY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    rmsZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud3D_rmsZ
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    convert
 * Signature: (IDDIDDIDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud3D_convert__IDDIDDIDD
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    convert
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud3D_convert___3D_3D_3D
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    histogram
 * Signature: ()Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CICloud3D_histogram
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud3D
 * Method:    fillHistogram
 * Signature: (Lhep/aida/IHistogram3D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud3D_fillHistogram
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
