/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CICloud */

#ifndef _Included_hep_aida_jni_CICloud
#define _Included_hep_aida_jni_CICloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CICloud
 * Method:    sumOfWeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud_sumOfWeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud
 * Method:    convertToHistogram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud_convertToHistogram
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud
 * Method:    isConverted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CICloud_isConverted
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud
 * Method:    maxEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CICloud_maxEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud
 * Method:    scale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud_scale
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
