/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CICloud1D */

#ifndef _Included_hep_aida_jni_CICloud1D
#define _Included_hep_aida_jni_CICloud1D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    fill
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud1D_fill__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    fill
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud1D_fill__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    lowerEdge
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_lowerEdge
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    upperEdge
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_upperEdge
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    value
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_value
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    weight
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_weight
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    mean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_mean
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    rms
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CICloud1D_rms
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    convert
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud1D_convert__IDD
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    convert
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud1D_convert___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    histogram
 * Signature: ()Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CICloud1D_histogram
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CICloud1D
 * Method:    fillHistogram
 * Signature: (Lhep/aida/IHistogram1D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CICloud1D_fillHistogram
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
