/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIDataStyle */

#ifndef _Included_hep_aida_jni_CIDataStyle
#define _Included_hep_aida_jni_CIDataStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    lineStyle
 * Signature: ()Lhep/aida/ILineStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataStyle_lineStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    markerStyle
 * Signature: ()Lhep/aida/IMarkerStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataStyle_markerStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    fillStyle
 * Signature: ()Lhep/aida/IFillStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataStyle_fillStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    setLineStyle
 * Signature: (Lhep/aida/ILineStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIDataStyle_setLineStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    setMarkerStyle
 * Signature: (Lhep/aida/IMarkerStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIDataStyle_setMarkerStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataStyle
 * Method:    setFillStyle
 * Signature: (Lhep/aida/IFillStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIDataStyle_setFillStyle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
