/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIDataPoint */

#ifndef _Included_hep_aida_jni_CIDataPoint
#define _Included_hep_aida_jni_CIDataPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIDataPoint
 * Method:    dimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIDataPoint_dimension
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIDataPoint
 * Method:    coordinate
 * Signature: (I)Lhep/aida/IMeasurement;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPoint_coordinate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
