/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIDataPointSetFactory */

#ifndef _Included_hep_aida_jni_CIDataPointSetFactory
#define _Included_hep_aida_jni_CIDataPointSetFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;I)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createY
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createY__Ljava_lang_String_2Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createY
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createY__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createY
 * Signature: (Ljava/lang/String;[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createY__Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createY
 * Signature: (Ljava/lang/String;[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createY__Ljava_lang_String_2_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createX
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createX__Ljava_lang_String_2Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createX
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createX__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createX
 * Signature: (Ljava/lang/String;[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createX__Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createX
 * Signature: (Ljava/lang/String;[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createX__Ljava_lang_String_2_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXY
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXY__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXY
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXY__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXY
 * Signature: (Ljava/lang/String;[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXY__Ljava_lang_String_2_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXY
 * Signature: (Ljava/lang/String;[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXY__Ljava_lang_String_2_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXYZ
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXYZ__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXYZ
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXYZ__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXYZ
 * Signature: (Ljava/lang/String;[D[D[D[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXYZ__Ljava_lang_String_2_3D_3D_3D_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createXYZ
 * Signature: (Ljava/lang/String;[D[D[D[D[D[D)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createXYZ__Ljava_lang_String_2_3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_createCopy
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    destroy
 * Signature: (Lhep/aida/IDataPointSet;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIDataPointSetFactory_destroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram1D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram2D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IHistogram3D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud1D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud1D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud1D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud2D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud2D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud2D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud3D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud3D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud3D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_ICloud3D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile1D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IProfile1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile1D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IProfile1D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile2D;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IProfile2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile2D;Ljava/lang/String;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_create__Ljava_lang_String_2Lhep_aida_IProfile2D_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    add
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_add
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    subtract
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_subtract
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    multiply
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_multiply
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    divide
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_divide
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIDataPointSetFactory
 * Method:    weightedMean
 * Signature: (Ljava/lang/String;Lhep/aida/IDataPointSet;Lhep/aida/IDataPointSet;)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIDataPointSetFactory_weightedMean
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
