/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFilter */

#ifndef _Included_hep_aida_jni_CIFilter
#define _Included_hep_aida_jni_CIFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFilter
 * Method:    initialize
 * Signature: (Lhep/aida/ITuple;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFilter_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFilter
 * Method:    accept
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFilter_accept
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFilter
 * Method:    expression
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFilter_expression
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
