/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFitFactory */

#ifndef _Included_hep_aida_jni_CIFitFactory
#define _Included_hep_aida_jni_CIFitFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFitFactory
 * Method:    createFitData
 * Signature: ()Lhep/aida/IFitData;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitFactory_createFitData
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitFactory
 * Method:    createFitter
 * Signature: ()Lhep/aida/IFitter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitFactory_createFitter__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitFactory
 * Method:    createFitter
 * Signature: (Ljava/lang/String;)Lhep/aida/IFitter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitFactory_createFitter__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitFactory
 * Method:    createFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/IFitter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitFactory_createFitter__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIFitFactory
 * Method:    createFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhep/aida/IFitter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitFactory_createFitter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
