/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFitData */

#ifndef _Included_hep_aida_jni_CIFitData
#define _Included_hep_aida_jni_CIFitData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create1DConnection
 * Signature: (Lhep/aida/IHistogram1D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create1DConnection__Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create1DConnection
 * Signature: (Lhep/aida/ICloud1D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create1DConnection__Lhep_aida_ICloud1D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create1DConnection
 * Signature: (Lhep/aida/IProfile1D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create1DConnection__Lhep_aida_IProfile1D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create1DConnection
 * Signature: (Lhep/aida/IDataPointSet;II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create1DConnection__Lhep_aida_IDataPointSet_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/IHistogram2D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/IHistogram2D;II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_IHistogram2D_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/ICloud2D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_ICloud2D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/ICloud2D;II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_ICloud2D_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/IProfile2D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_IProfile2D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/IProfile2D;II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_IProfile2D_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create2DConnection
 * Signature: (Lhep/aida/IDataPointSet;III)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create2DConnection__Lhep_aida_IDataPointSet_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create3DConnection
 * Signature: (Lhep/aida/IHistogram3D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create3DConnection__Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create3DConnection
 * Signature: (Lhep/aida/IHistogram3D;III)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create3DConnection__Lhep_aida_IHistogram3D_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create3DConnection
 * Signature: (Lhep/aida/ICloud3D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create3DConnection__Lhep_aida_ICloud3D_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create3DConnection
 * Signature: (Lhep/aida/ICloud3D;III)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create3DConnection__Lhep_aida_ICloud3D_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    create3DConnection
 * Signature: (Lhep/aida/IDataPointSet;IIII)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_create3DConnection__Lhep_aida_IDataPointSet_2IIII
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    createConnection
 * Signature: (Lhep/aida/ITuple;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_createConnection__Lhep_aida_ITuple_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    createConnection
 * Signature: (Lhep/aida/ITuple;[Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_createConnection__Lhep_aida_ITuple_2_3Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    createConnection
 * Signature: (Lhep/aida/IDataPointSet;[II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_createConnection__Lhep_aida_IDataPointSet_2_3II
  (JNIEnv *, jobject, jobject, jintArray, jint);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitData_reset
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    dimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFitData_dimension
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    dataDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitData_dataDescription
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitData
 * Method:    range
 * Signature: (I)Lhep/aida/IRangeSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitData_range
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
