/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFitParameterSettings */

#ifndef _Included_hep_aida_jni_CIFitParameterSettings
#define _Included_hep_aida_jni_CIFitParameterSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitParameterSettings_name
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    stepSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitParameterSettings_stepSize
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    upperBound
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitParameterSettings_upperBound
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    lowerBound
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitParameterSettings_lowerBound
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    isBound
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFitParameterSettings_isBound
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    isFixed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFitParameterSettings_isFixed
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    setStepSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_setStepSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    setBounds
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_setBounds
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    removeBounds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_removeBounds
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    setFixed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_setFixed
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    setLowerBound
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_setLowerBound
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    setUpperBound
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_setUpperBound
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIFitParameterSettings
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitParameterSettings_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
