/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFillStyle */

#ifndef _Included_hep_aida_jni_CIFillStyle
#define _Included_hep_aida_jni_CIFillStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFillStyle
 * Method:    availablePatterns
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFillStyle_availablePatterns
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFillStyle
 * Method:    pattern
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFillStyle_pattern
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFillStyle
 * Method:    setPattern
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFillStyle_setPattern
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
