/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFitResult */

#ifndef _Included_hep_aida_jni_CIFitResult
#define _Included_hep_aida_jni_CIFitResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFitResult_isValid
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fitStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFitResult_fitStatus
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fittedFunction
 * Signature: ()Lhep/aida/IFunction;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitResult_fittedFunction
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    quality
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitResult_quality
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    ndf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFitResult_ndf
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    covMatrixElement
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitResult_covMatrixElement
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fitMethodName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitResult_fitMethodName
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    engineName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitResult_engineName
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    dataDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitResult_dataDescription
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    constraints
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFitResult_constraints
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fitParameterSettings
 * Signature: (Ljava/lang/String;)Lhep/aida/IFitParameterSettings;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitResult_fitParameterSettings
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fittedParameters
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFitResult_fittedParameters
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fittedParameterNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFitResult_fittedParameterNames
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    fittedParameter
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFitResult_fittedParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    errors
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFitResult_errors
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    errorsPlus
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFitResult_errorsPlus
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitResult
 * Method:    errorsMinus
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFitResult_errorsMinus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
