/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFitter */

#ifndef _Included_hep_aida_jni_CIFitter
#define _Included_hep_aida_jni_CIFitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IFitData;Lhep/aida/IFunction;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IFitData_2Lhep_aida_IFunction_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IBaseHistogram;Lhep/aida/IFunction;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IBaseHistogram_2Lhep_aida_IFunction_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IBaseHistogram;Ljava/lang/String;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IBaseHistogram_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IBaseHistogram;Ljava/lang/String;[D)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IBaseHistogram_2Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jobject, jstring, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IDataPointSet;Lhep/aida/IFunction;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IDataPointSet_2Lhep_aida_IFunction_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IDataPointSet;Ljava/lang/String;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IDataPointSet_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IDataPointSet;Ljava/lang/String;[D)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IDataPointSet_2Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jobject, jstring, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IFitData;Ljava/lang/String;)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IFitData_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fit
 * Signature: (Lhep/aida/IFitData;Ljava/lang/String;[D)Lhep/aida/IFitResult;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fit__Lhep_aida_IFitData_2Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jobject, jstring, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    setEngine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_setEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    engineName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitter_engineName
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fitParameterSettings
 * Signature: (Ljava/lang/String;)Lhep/aida/IFitParameterSettings;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_fitParameterSettings
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    listParameterSettings
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFitter_listParameterSettings
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    resetParameterSettings
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_resetParameterSettings
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    setConstraint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_setConstraint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    constraints
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFitter_constraints
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    resetConstraints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_resetConstraints
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    setFitMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_setFitMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    fitMethodName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFitter_fitMethodName
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    createScan1D
 * Signature: (Lhep/aida/IFitData;Lhep/aida/IFunction;Ljava/lang/String;IDD)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_createScan1D
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    createContour
 * Signature: (Lhep/aida/IFitData;Lhep/aida/IFitResult;Ljava/lang/String;Ljava/lang/String;ID)Lhep/aida/IDataPointSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFitter_createContour
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jint, jdouble);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    setUseFunctionGradient
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFitter_setUseFunctionGradient
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CIFitter
 * Method:    useFunctionGradient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFitter_useFunctionGradient
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
