/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFunctionFactory */

#ifndef _Included_hep_aida_jni_CIFunctionFactory
#define _Included_hep_aida_jni_CIFunctionFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFunctionFactory
 * Method:    createFunctionByName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/IFunction;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunctionFactory_createFunctionByName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIFunctionFactory
 * Method:    createFunctionFromScript
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhep/aida/IFunction;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunctionFactory_createFunctionFromScript__Ljava_lang_String_2ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIFunctionFactory
 * Method:    createFunctionFromScript
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhep/aida/IFunction;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunctionFactory_createFunctionFromScript__Ljava_lang_String_2ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIFunctionFactory
 * Method:    cloneFunction
 * Signature: (Ljava/lang/String;Lhep/aida/IFunction;)Lhep/aida/IFunction;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunctionFactory_cloneFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIFunctionFactory
 * Method:    catalog
 * Signature: ()Lhep/aida/IFunctionCatalog;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunctionFactory_catalog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
