/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIFunction */

#ifndef _Included_hep_aida_jni_CIFunction
#define _Included_hep_aida_jni_CIFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFunction_title
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFunction_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    value
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFunction_value
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    dimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFunction_dimension
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    isEqual
 * Signature: (Lhep/aida/IFunction;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFunction_isEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    gradient
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFunction_gradient
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    providesGradient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIFunction_providesGradient
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    variableName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFunction_variableName
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    variableNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFunction_variableNames
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    setParameters
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFunction_setParameters
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    parameters
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIFunction_parameters
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    numberOfParameters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFunction_numberOfParameters
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    parameterNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIFunction_parameterNames
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    setParameter
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIFunction_setParameter
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    parameter
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIFunction_parameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    indexOfParameter
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIFunction_indexOfParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    annotation
 * Signature: ()Lhep/aida/IAnnotation;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIFunction_annotation
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIFunction
 * Method:    codeletString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIFunction_codeletString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
