/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIHistogram1D */

#ifndef _Included_hep_aida_jni_CIHistogram1D
#define _Included_hep_aida_jni_CIHistogram1D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    fill
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram1D_fill__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    fill
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram1D_fill__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    binMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram1D_binMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    binEntries
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram1D_binEntries
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    binHeight
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram1D_binHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    binError
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram1D_binError
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    mean
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram1D_mean
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    rms
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram1D_rms
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    axis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogram1D_axis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    coordToIndex
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram1D_coordToIndex
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogram1D
 * Method:    add
 * Signature: (Lhep/aida/IHistogram1D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram1D_add
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
