/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIHistogram */

#ifndef _Included_hep_aida_jni_CIHistogram
#define _Included_hep_aida_jni_CIHistogram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    allEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram_allEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    extraEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIHistogram_extraEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    equivalentBinEntries
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_equivalentBinEntries
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    sumBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_sumBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    sumAllBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_sumAllBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    sumExtraBinHeights
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_sumExtraBinHeights
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    minBinHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_minBinHeight
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    maxBinHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIHistogram_maxBinHeight
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIHistogram
 * Method:    scale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogram_scale
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
