/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIHistogramFactory */

#ifndef _Included_hep_aida_jni_CIHistogramFactory
#define _Included_hep_aida_jni_CIHistogramFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    destroy
 * Signature: (Lhep/aida/IBaseHistogram;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIHistogramFactory_destroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ICloud1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud1D__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lhep/aida/ICloud1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud1D__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Lhep/aida/ICloud1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud1D__Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud1D
 * Signature: (Ljava/lang/String;)Lhep/aida/ICloud1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud1D__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud1D;)Lhep/aida/ICloud1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_ICloud1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ICloud2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud2D__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lhep/aida/ICloud2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud2D__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Lhep/aida/ICloud2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud2D__Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud2D
 * Signature: (Ljava/lang/String;)Lhep/aida/ICloud2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud2D__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud2D;)Lhep/aida/ICloud2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_ICloud2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ICloud3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud3D__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lhep/aida/ICloud3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud3D__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Lhep/aida/ICloud3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud3D__Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCloud3D
 * Signature: (Ljava/lang/String;)Lhep/aida/ICloud3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCloud3D__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/ICloud3D;)Lhep/aida/ICloud3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_ICloud3D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDD)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram1D__Ljava_lang_String_2Ljava_lang_String_2IDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDLjava/lang/String;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram1D__Ljava_lang_String_2Ljava_lang_String_2IDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram1D
 * Signature: (Ljava/lang/String;IDD)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram1D__Ljava_lang_String_2IDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram1D__Ljava_lang_String_2Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DLjava/lang/String;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram1D__Ljava_lang_String_2Ljava_lang_String_2_3DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDD)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDLjava/lang/String;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram2D
 * Signature: (Ljava/lang/String;IDDIDD)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram2D__Ljava_lang_String_2IDDIDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[DLjava/lang/String;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDIDD)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram3D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDIDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDIDDLjava/lang/String;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram3D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDIDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram3D
 * Signature: (Ljava/lang/String;IDDIDDIDD)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram3D__Ljava_lang_String_2IDDIDDIDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[D)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram3D__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createHistogram3D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D[DLjava/lang/String;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createHistogram3D__Ljava_lang_String_2Ljava_lang_String_2_3D_3D_3DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDD)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2IDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDLjava/lang/String;)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2IDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDDD)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2IDDDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDDDLjava/lang/String;)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2IDDDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DLjava/lang/String;)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2_3DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DDD)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2_3DDD
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DDDLjava/lang/String;)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2Ljava_lang_String_2_3DDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;IDD)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2IDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile1D
 * Signature: (Ljava/lang/String;IDDDD)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile1D__Ljava_lang_String_2IDDDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile1D;)Lhep/aida/IProfile1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_IProfile1D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDD)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDLjava/lang/String;)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDDD)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDDD
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDIDDDDLjava/lang/String;)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2IDDIDDDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[D)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3D
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[DLjava/lang/String;)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[DDD)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3DDD
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D[DDDLjava/lang/String;)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2Ljava_lang_String_2_3D_3DDDLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jdoubleArray, jdouble, jdouble, jstring);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;IDDIDD)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2IDDIDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createProfile2D
 * Signature: (Ljava/lang/String;IDDIDDDD)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createProfile2D__Ljava_lang_String_2IDDIDDDD
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    createCopy
 * Signature: (Ljava/lang/String;Lhep/aida/IProfile2D;)Lhep/aida/IProfile2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_createCopy__Ljava_lang_String_2Lhep_aida_IProfile2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    add
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;Lhep/aida/IHistogram1D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_add__Ljava_lang_String_2Lhep_aida_IHistogram1D_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    subtract
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;Lhep/aida/IHistogram1D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_subtract__Ljava_lang_String_2Lhep_aida_IHistogram1D_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    multiply
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;Lhep/aida/IHistogram1D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_multiply__Ljava_lang_String_2Lhep_aida_IHistogram1D_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    divide
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram1D;Lhep/aida/IHistogram1D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_divide__Ljava_lang_String_2Lhep_aida_IHistogram1D_2Lhep_aida_IHistogram1D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    add
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_add__Ljava_lang_String_2Lhep_aida_IHistogram2D_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    subtract
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_subtract__Ljava_lang_String_2Lhep_aida_IHistogram2D_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    multiply
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_multiply__Ljava_lang_String_2Lhep_aida_IHistogram2D_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    divide
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_divide__Ljava_lang_String_2Lhep_aida_IHistogram2D_2Lhep_aida_IHistogram2D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    add
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_add__Ljava_lang_String_2Lhep_aida_IHistogram3D_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    subtract
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_subtract__Ljava_lang_String_2Lhep_aida_IHistogram3D_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    multiply
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_multiply__Ljava_lang_String_2Lhep_aida_IHistogram3D_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    divide
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram3D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_divide__Ljava_lang_String_2Lhep_aida_IHistogram3D_2Lhep_aida_IHistogram3D_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    projectionX
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_projectionX
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    projectionY
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_projectionY
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceX
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;I)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceX__Ljava_lang_String_2Lhep_aida_IHistogram2D_2I
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceY
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;I)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceY__Ljava_lang_String_2Lhep_aida_IHistogram2D_2I
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceX
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;II)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceX__Ljava_lang_String_2Lhep_aida_IHistogram2D_2II
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceY
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram2D;II)Lhep/aida/IHistogram1D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceY__Ljava_lang_String_2Lhep_aida_IHistogram2D_2II
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    projectionXY
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_projectionXY
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    projectionXZ
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_projectionXZ
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    projectionYZ
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_projectionYZ
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceXY
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;II)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceXY
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceXZ
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;II)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceXZ
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIHistogramFactory
 * Method:    sliceYZ
 * Signature: (Ljava/lang/String;Lhep/aida/IHistogram3D;II)Lhep/aida/IHistogram2D;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIHistogramFactory_sliceYZ
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
