/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIInfoStyle */

#ifndef _Included_hep_aida_jni_CIInfoStyle
#define _Included_hep_aida_jni_CIInfoStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIInfoStyle
 * Method:    textStyle
 * Signature: ()Lhep/aida/ITextStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIInfoStyle_textStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIInfoStyle
 * Method:    setTextStyle
 * Signature: (Lhep/aida/ITextStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIInfoStyle_setTextStyle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
