/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIInfo */

#ifndef _Included_hep_aida_jni_CIInfo
#define _Included_hep_aida_jni_CIInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIInfo
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIInfo_clear
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIInfo
 * Method:    addText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIInfo_addText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIInfo
 * Method:    addLegend
 * Signature: (Lhep/aida/IMarkerStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIInfo_addLegend__Lhep_aida_IMarkerStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIInfo
 * Method:    addLegend
 * Signature: (Lhep/aida/ILineStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIInfo_addLegend__Lhep_aida_ILineStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIInfo
 * Method:    addLegend
 * Signature: (Lhep/aida/IFillStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIInfo_addLegend__Lhep_aida_IFillStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
