/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CILineStyle */

#ifndef _Included_hep_aida_jni_CILineStyle
#define _Included_hep_aida_jni_CILineStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CILineStyle
 * Method:    availableLineTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CILineStyle_availableLineTypes
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CILineStyle
 * Method:    lineType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CILineStyle_lineType
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CILineStyle
 * Method:    thickness
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CILineStyle_thickness
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CILineStyle
 * Method:    setLineType
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CILineStyle_setLineType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CILineStyle
 * Method:    setThickness
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CILineStyle_setThickness
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
