/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIMarkerStyle */

#ifndef _Included_hep_aida_jni_CIMarkerStyle
#define _Included_hep_aida_jni_CIMarkerStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIMarkerStyle
 * Method:    availableShapes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIMarkerStyle_availableShapes
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIMarkerStyle
 * Method:    shape
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIMarkerStyle_shape
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIMarkerStyle
 * Method:    setShape
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIMarkerStyle_setShape
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
