/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIManagedObject */

#ifndef _Included_hep_aida_jni_CIManagedObject
#define _Included_hep_aida_jni_CIManagedObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIManagedObject
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIManagedObject_name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
