/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIMeasurement */

#ifndef _Included_hep_aida_jni_CIMeasurement
#define _Included_hep_aida_jni_CIMeasurement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    value
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIMeasurement_value
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    errorPlus
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIMeasurement_errorPlus
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    errorMinus
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIMeasurement_errorMinus
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    setValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIMeasurement_setValue
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    setErrorPlus
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIMeasurement_setErrorPlus
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIMeasurement
 * Method:    setErrorMinus
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIMeasurement_setErrorMinus
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
