/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIModelFunction */

#ifndef _Included_hep_aida_jni_CIModelFunction
#define _Included_hep_aida_jni_CIModelFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    providesNormalization
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIModelFunction_providesNormalization
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    normalize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIModelFunction_normalize
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    isNormalized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIModelFunction_isNormalized
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    parameterGradient
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_aida_jni_CIModelFunction_parameterGradient
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    providesParameterGradient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIModelFunction_providesParameterGradient
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    normalizationRange
 * Signature: (I)Lhep/aida/IRangeSet;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIModelFunction_normalizationRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    includeNormalizationAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIModelFunction_includeNormalizationAll
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIModelFunction
 * Method:    excludeNormalizationAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIModelFunction_excludeNormalizationAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
