/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIPlotterLayout */

#ifndef _Included_hep_aida_jni_CIPlotterLayout
#define _Included_hep_aida_jni_CIPlotterLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIPlotterLayout
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterLayout_reset
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterLayout
 * Method:    setParameter
 * Signature: (Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterLayout_setParameter
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterLayout
 * Method:    parameterValue
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIPlotterLayout_parameterValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterLayout
 * Method:    availableParameters
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIPlotterLayout_availableParameters
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
