/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIPlotterStyle */

#ifndef _Included_hep_aida_jni_CIPlotterStyle
#define _Included_hep_aida_jni_CIPlotterStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    dataStyle
 * Signature: ()Lhep/aida/IDataStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_dataStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    xAxisStyle
 * Signature: ()Lhep/aida/IAxisStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_xAxisStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    yAxisStyle
 * Signature: ()Lhep/aida/IAxisStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_yAxisStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    zAxisStyle
 * Signature: ()Lhep/aida/IAxisStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_zAxisStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    titleStyle
 * Signature: ()Lhep/aida/ITitleStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_titleStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    infoStyle
 * Signature: ()Lhep/aida/IInfoStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterStyle_infoStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setDataStyle
 * Signature: (Lhep/aida/IDataStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setDataStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setAxisStyleX
 * Signature: (Lhep/aida/IAxisStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setAxisStyleX
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setAxisStyleY
 * Signature: (Lhep/aida/IAxisStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setAxisStyleY
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setAxisStyleZ
 * Signature: (Lhep/aida/IAxisStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setAxisStyleZ
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setTitleStyle
 * Signature: (Lhep/aida/ITitleStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setTitleStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterStyle
 * Method:    setInfoStyle
 * Signature: (Lhep/aida/IInfoStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CIPlotterStyle_setInfoStyle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
