/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIPlotterFactory */

#ifndef _Included_hep_aida_jni_CIPlotterFactory
#define _Included_hep_aida_jni_CIPlotterFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    create
 * Signature: ()Lhep/aida/IPlotter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    create
 * Signature: (Ljava/lang/String;)Lhep/aida/IPlotter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createMarkerStyle
 * Signature: ()Lhep/aida/IMarkerStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createMarkerStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createTextStyle
 * Signature: ()Lhep/aida/ITextStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createTextStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createLineStyle
 * Signature: ()Lhep/aida/ILineStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createLineStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createFillStyle
 * Signature: ()Lhep/aida/IFillStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createFillStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createDataStyle
 * Signature: ()Lhep/aida/IDataStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createDataStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createAxisStyle
 * Signature: ()Lhep/aida/IAxisStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createAxisStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createTitleStyle
 * Signature: ()Lhep/aida/ITitleStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createTitleStyle
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterFactory
 * Method:    createPlotterStyle
 * Signature: ()Lhep/aida/IPlotterStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterFactory_createPlotterStyle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
