/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIPlotterRegion */

#ifndef _Included_hep_aida_jni_CIPlotterRegion
#define _Included_hep_aida_jni_CIPlotterRegion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IBaseHistogram;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IBaseHistogram_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IBaseHistogram;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IBaseHistogram_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IBaseHistogram;Lhep/aida/IPlotterStyle;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IBaseHistogram_2Lhep_aida_IPlotterStyle_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IBaseHistogram;Lhep/aida/IPlotterStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IBaseHistogram_2Lhep_aida_IPlotterStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IFunction;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IFunction_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IFunction;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IFunction_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IFunction;Lhep/aida/IPlotterStyle;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IFunction_2Lhep_aida_IPlotterStyle_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IFunction;Lhep/aida/IPlotterStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IFunction_2Lhep_aida_IPlotterStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IDataPointSet;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IDataPointSet_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IDataPointSet;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IDataPointSet_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IDataPointSet;Lhep/aida/IPlotterStyle;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IDataPointSet_2Lhep_aida_IPlotterStyle_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    plot
 * Signature: (Lhep/aida/IDataPointSet;Lhep/aida/IPlotterStyle;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_plot__Lhep_aida_IDataPointSet_2Lhep_aida_IPlotterStyle_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    remove
 * Signature: (Lhep/aida/IBaseHistogram;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_remove__Lhep_aida_IBaseHistogram_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    remove
 * Signature: (Lhep/aida/IFunction;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_remove__Lhep_aida_IFunction_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    remove
 * Signature: (Lhep/aida/IDataPointSet;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_remove__Lhep_aida_IDataPointSet_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_clear
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setParameter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setParameter__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setParameter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setParameter__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    parameterValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CIPlotterRegion_parameterValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    availableParameterOptions
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIPlotterRegion_availableParameterOptions
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    availableParameters
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CIPlotterRegion_availableParameters
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    style
 * Signature: ()Lhep/aida/IPlotterStyle;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterRegion_style
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setStyle
 * Signature: (Lhep/aida/IPlotterStyle;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    applyStyle
 * Signature: (Lhep/aida/IPlotterStyle;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_applyStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setXLimits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setXLimits__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setXLimits
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setXLimits__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setXLimits
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setXLimits__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setYLimits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setYLimits__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setYLimits
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setYLimits__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setYLimits
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setYLimits__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setZLimits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setZLimits__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setZLimits
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setZLimits__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setZLimits
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setZLimits__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    layout
 * Signature: ()Lhep/aida/IPlotterLayout;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterRegion_layout
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    setLayout
 * Signature: (Lhep/aida/IPlotterLayout;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIPlotterRegion_setLayout
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CIPlotterRegion
 * Method:    info
 * Signature: ()Lhep/aida/IInfo;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIPlotterRegion_info
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
