/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CIProfile2D */

#ifndef _Included_hep_aida_jni_CIProfile2D
#define _Included_hep_aida_jni_CIProfile2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    fill
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIProfile2D_fill__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    fill
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIProfile2D_fill__DDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binMeanX
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binMeanX
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binMeanY
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binMeanY
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binEntries
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile2D_binEntries
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binEntriesX
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile2D_binEntriesX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binEntriesY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile2D_binEntriesY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binHeight
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binHeight
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binHeightX
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binHeightX
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binHeightY
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binHeightY
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binError
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binError
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    binRms
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_binRms
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    meanX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_meanX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    meanY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_meanY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    rmsX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_rmsX
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    rmsY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CIProfile2D_rmsY
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    xAxis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIProfile2D_xAxis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    yAxis
 * Signature: ()Lhep/aida/IAxis;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CIProfile2D_yAxis
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    coordToIndexX
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile2D_coordToIndexX
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    coordToIndexY
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CIProfile2D_coordToIndexY
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CIProfile2D
 * Method:    add
 * Signature: (Lhep/aida/IProfile2D;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CIProfile2D_add
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
