/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CITextStyle */

#ifndef _Included_hep_aida_jni_CITextStyle
#define _Included_hep_aida_jni_CITextStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    availableFonts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITextStyle_availableFonts
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    fontSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITextStyle_fontSize
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setFontSize
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setFontSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    font
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITextStyle_font
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setFont
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    isBold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_isBold
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    isItalic
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_isItalic
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    isUnderlined
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_isUnderlined
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setBold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setBold__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setBold
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setBold__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setItalic
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setItalic__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setItalic
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setItalic__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setUnderlined
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setUnderlined__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITextStyle
 * Method:    setUnderlined
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITextStyle_setUnderlined__Z
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
