/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CITree */

#ifndef _Included_hep_aida_jni_CITree
#define _Included_hep_aida_jni_CITree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CITree
 * Method:    storeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITree_storeName
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    find
 * Signature: (Ljava/lang/String;)Lhep/aida/IManagedObject;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITree_find
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    findTree
 * Signature: (Ljava/lang/String;)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITree_findTree
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    cd
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_cd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    pwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITree_pwd
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    ls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_ls__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    ls
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_ls__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    ls
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_ls__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    ls
 * Signature: (Ljava/lang/String;ZLjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_ls__Ljava_lang_String_2ZLjava_io_OutputStream_2
  (JNIEnv *, jobject, jstring, jboolean, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectNames__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectNames
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectNames__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectNames
 * Signature: (Ljava/lang/String;Z)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectNames__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectTypes__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectTypes
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectTypes__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    listObjectTypes
 * Signature: (Ljava/lang/String;Z)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITree_listObjectTypes__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    mkdir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_mkdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    mkdirs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_mkdirs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    rmdir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_rmdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    rm
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_rm
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    findPath
 * Signature: (Lhep/aida/IManagedObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITree_findPath
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    mv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_mv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_commit
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    setOverwrite
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_setOverwrite__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    setOverwrite
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_setOverwrite__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    cp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_cp__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    cp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_cp__Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    symlink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_symlink
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    mount
 * Signature: (Ljava/lang/String;Lhep/aida/ITree;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_mount
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    unmount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_unmount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITree
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITree_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
