/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CITreeFactory */

#ifndef _Included_hep_aida_jni_CITreeFactory
#define _Included_hep_aida_jni_CITreeFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: ()Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: (Ljava/lang/String;)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZ)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__Ljava_lang_String_2Ljava_lang_String_2ZZ
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     hep_aida_jni_CITreeFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZLjava/lang/String;)Lhep/aida/ITree;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITreeFactory_create__Ljava_lang_String_2Ljava_lang_String_2ZZLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
