/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CITuple */

#ifndef _Included_hep_aida_jni_CITuple
#define _Included_hep_aida_jni_CITuple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CITuple
 * Method:    title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITuple_title
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    annotation
 * Signature: ()Lhep/aida/IAnnotation;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITuple_annotation
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__ID
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IS
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IC
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IB
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill__ILjava_lang_Object_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    fill
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_fill___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    addRow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_addRow
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    resetRow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_resetRow
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_reset
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    rows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CITuple_rows
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_start
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    skip
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_skip
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    next
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITuple_next
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    setRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_setRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    findColumn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CITuple_findColumn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITuple_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_hep_aida_jni_CITuple_getFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CITuple_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_hep_aida_jni_CITuple_getShort
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hep_aida_jni_CITuple_getLong
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getChar
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_hep_aida_jni_CITuple_getChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_hep_aida_jni_CITuple_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hep_aida_jni_CITuple_getBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITuple_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getObject
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITuple_getObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    getTuple
 * Signature: (I)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITuple_getTuple
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_aida_jni_CITuple_columns
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_aida_jni_CITuple_columnName
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITuple_columnNames
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnType
 * Signature: (I)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_hep_aida_jni_CITuple_columnType
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnTypes
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_hep_aida_jni_CITuple_columnTypes
  (JNIEnv *, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITuple_columnMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITuple_columnMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITuple_columnMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    columnRms
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hep_aida_jni_CITuple_columnRms
  (JNIEnv *, jobject, jint);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram1D;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram1D_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram1D;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram1D_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram1D;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram1D_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IHistogram3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IHistogram3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud1D;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud1D_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud1D;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud1D_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud1D;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud1D_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/ICloud3D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_ICloud3D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile1D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile1D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITuple
 * Method:    project
 * Signature: (Lhep/aida/IProfile2D;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IEvaluator;Lhep/aida/IFilter;Lhep/aida/IEvaluator;)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CITuple_project__Lhep_aida_IProfile2D_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IEvaluator_2Lhep_aida_IFilter_2Lhep_aida_IEvaluator_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
