/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CITupleFactory */

#ifndef _Included_hep_aida_jni_CITupleFactory
#define _Included_hep_aida_jni_CITupleFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Class;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_create__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_String_2_3Ljava_lang_Class_2
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Class;Ljava/lang/String;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_create__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_String_2_3Ljava_lang_Class_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobjectArray, jstring);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_create__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_create__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createChained
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lhep/aida/ITuple;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createChained__Ljava_lang_String_2Ljava_lang_String_2_3Lhep_aida_ITuple_2
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createChained
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createChained__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createFiltered
 * Signature: (Ljava/lang/String;Lhep/aida/ITuple;Lhep/aida/IFilter;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createFiltered__Ljava_lang_String_2Lhep_aida_ITuple_2Lhep_aida_IFilter_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createFiltered
 * Signature: (Ljava/lang/String;Lhep/aida/ITuple;Lhep/aida/IFilter;[Ljava/lang/String;)Lhep/aida/ITuple;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createFiltered__Ljava_lang_String_2Lhep_aida_ITuple_2Lhep_aida_IFilter_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobject, jobject, jobjectArray);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createFilter
 * Signature: (Ljava/lang/String;)Lhep/aida/IFilter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createFilter__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createFilter
 * Signature: (Ljava/lang/String;I)Lhep/aida/IFilter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createFilter__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createFilter
 * Signature: (Ljava/lang/String;II)Lhep/aida/IFilter;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createFilter__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     hep_aida_jni_CITupleFactory
 * Method:    createEvaluator
 * Signature: (Ljava/lang/String;)Lhep/aida/IEvaluator;
 */
JNIEXPORT jobject JNICALL Java_hep_aida_jni_CITupleFactory_createEvaluator
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
