/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_aida_jni_CProxy */

#ifndef _Included_hep_aida_jni_CProxy
#define _Included_hep_aida_jni_CProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_aida_jni_CProxy
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hep_aida_jni_CProxy_finalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
