/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_graphics_heprep_jni_JG4CommandDriver */

#ifndef _Included_hep_graphics_heprep_jni_JG4CommandDriver
#define _Included_hep_graphics_heprep_jni_JG4CommandDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hep_graphics_heprep_jni_JG4CommandDriver
 * Method:    immediateCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hep_graphics_heprep_jni_JG4CommandDriver_immediateCommand
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
