# 
# Makefile for the HBook-AIDA library
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.6 2001/04/18 14:36:48 duns Exp $
#

#
# User Configuration: Define targets
#
INCLUDEDIRS = $(FREEHEP)/org/freehep/jni
INCLUDELIBS = FHJNI
OBJS = JHBookAida
OBJS += JHBookHistogram 
OBJS += JHBookTuple
OBJS += JHBookAdvanced 
#OBJS += WeightFunction  
LIBS = FHHBook
DLLS = FHHBook
EXE = CHBookAidaTest
TEST = HBookTest

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
