#
# Makefile for the Runs utility
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.1 2004/02/19 23:12:11 duns Exp $
#

#
# User Configuration: Define targets
#
OBJS  = runs
#LIBS = runs
#DLLS = runs
#EXE = runs
TEST =
LINKNOJAVA = true

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
