/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runs */

#ifndef _Included_runs
#define _Included_runs
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: libname */
/*
 * Class:     runs
 * Method:    main
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_runs_main
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
