#
# Makefile for the HEPREP-CONFIG utility
#
# Author: Mark Donszelmann
# Version: $Id: GNUmakefile,v 1.1 2004/10/26 21:11:08 duns Exp $
#

#
# User Configuration: Define targets
#
OBJS  = heprep-config
LIBS = heprep-config
DLLS = heprep-config
EXE = heprep-config
TEST =
LINKNOJAVA = true

#
# No User Configuration below
#

include $(FREEHEP)/config/common.gmk
