/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hep_io_hbook_Hbook */

#ifndef _Included_hep_io_hbook_Hbook
#define _Included_hep_io_hbook_Hbook
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: init */
/* Inaccessible static: luns */
/*
 * Class:     hep_io_hbook_Hbook
 * Method:    getCWDataDouble
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_hep_io_hbook_Hbook_getCWDataDouble
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    getCWDataInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_hep_io_hbook_Hbook_getCWDataInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    getCWDataLong
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_hep_io_hbook_Hbook_getCWDataLong
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    getCWDataString
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hep_io_hbook_Hbook_getCWDataString
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    setCWEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_setCWEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    getRWData
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_hep_io_hbook_Hbook_getRWData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    setRWEvent
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_setRWEvent
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    CWClearMap
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_CWClearMap
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    CWMap
 * Signature: (ILjava/lang/String;JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_CWMap
  (JNIEnv *, jclass, jint, jstring, jlong, jstring, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    CWgetMinMax
 * Signature: (IJIIIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_io_hbook_Hbook_CWgetMinMax
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    CWrebin
 * Signature: (IJIIIIIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_io_hbook_Hbook_CWrebin
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    Hist1DData
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_io_hbook_Hbook_Hist1DData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    Hist1DErrors
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_io_hbook_Hbook_Hist1DErrors
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    Hist2DData
 * Signature: (III)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_hep_io_hbook_Hbook_Hist2DData
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    Hist2DErrors
 * Signature: (III)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_hep_io_hbook_Hbook_Hist2DErrors
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    RWrebin
 * Signature: (IIIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hep_io_hbook_Hbook_RWrebin
  (JNIEnv *, jclass, jint, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    allocBuffer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hep_io_hbook_Hbook_allocBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_delete
  (JNIEnv *, jclass, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    freeBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_freeBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hep_io_hbook_Hbook_init
  (JNIEnv *, jclass);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    visitChildren
 * Signature: (Lhep/io/hbook/HbookObject;)I
 */
JNIEXPORT jint JNICALL Java_hep_io_hbook_Hbook_visitChildren
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    closeFile
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hep_io_hbook_Hbook_closeFile
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     hep_io_hbook_Hbook
 * Method:    openFile
 * Signature: (Ljava/lang/String;II)Lhep/io/hbook/CompositeHbookObject;
 */
JNIEXPORT jobject JNICALL Java_hep_io_hbook_Hbook_openFile
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
