package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepPointHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Point
abstract public class HepRepPointHelper
{
  private static String  _id = "IDL:HepRepPoint:1.0";

  public static void insert (org.omg.CORBA.Any a, hep.graphics.heprep.corba.idl.HepRepPoint that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hep.graphics.heprep.corba.idl.HepRepPoint extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[0] = new org.omg.CORBA.StructMember (
            "x",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[1] = new org.omg.CORBA.StructMember (
            "y",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "z",
            _tcOf_members0,
            null);
          _tcOf_members0 = hep.graphics.heprep.corba.idl.HepRepAttValueHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (hep.graphics.heprep.corba.idl.HepRepAttValueListHelper.id (), "HepRepAttValueList", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "attValues",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (hep.graphics.heprep.corba.idl.HepRepPointHelper.id (), "HepRepPoint", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hep.graphics.heprep.corba.idl.HepRepPoint read (org.omg.CORBA.portable.InputStream istream)
  {
    hep.graphics.heprep.corba.idl.HepRepPoint value = new hep.graphics.heprep.corba.idl.HepRepPoint ();
    value.x = istream.read_double ();
    value.y = istream.read_double ();
    value.z = istream.read_double ();
    value.attValues = hep.graphics.heprep.corba.idl.HepRepAttValueListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hep.graphics.heprep.corba.idl.HepRepPoint value)
  {
    ostream.write_double (value.x);
    ostream.write_double (value.y);
    ostream.write_double (value.z);
    hep.graphics.heprep.corba.idl.HepRepAttValueListHelper.write (ostream, value.attValues);
  }

}
