package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepTreeIDListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/

abstract public class HepRepTreeIDListHelper
{
  private static String  _id = "IDL:HepRepTreeIDList:1.0";

  public static void insert (org.omg.CORBA.Any a, hep.graphics.heprep.corba.idl.HepRepTreeID[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hep.graphics.heprep.corba.idl.HepRepTreeID[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (hep.graphics.heprep.corba.idl.HepRepTreeIDListHelper.id (), "HepRepTreeIDList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hep.graphics.heprep.corba.idl.HepRepTreeID[] read (org.omg.CORBA.portable.InputStream istream)
  {
    hep.graphics.heprep.corba.idl.HepRepTreeID value[] = null;
    int _len0 = istream.read_long ();
    value = new hep.graphics.heprep.corba.idl.HepRepTreeID[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hep.graphics.heprep.corba.idl.HepRepTreeID[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.write (ostream, value[_i0]);
  }

}
