package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRep.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:16 AM PDT
*/


// HepRep
public interface HepRep extends HepRepOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HepRep
