package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepPoint.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Point
public final class HepRepPoint implements org.omg.CORBA.portable.IDLEntity
{
  public double x = (double)0;
  public double y = (double)0;
  public double z = (double)0;
  public hep.graphics.heprep.corba.idl.HepRepAttValue attValues[] = null;

  public HepRepPoint ()
  {
  } // ctor

  public HepRepPoint (double _x, double _y, double _z, hep.graphics.heprep.corba.idl.HepRepAttValue[] _attValues)
  {
    x = _x;
    y = _y;
    z = _z;
    attValues = _attValues;
  } // ctor

} // class HepRepPoint
