package hep.graphics.heprep.corba.idl;

/**
* hep/graphics/heprep/corba/idl/HepRepTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Type
public final class HepRepTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public hep.graphics.heprep.corba.idl.HepRepType value = null;

  public HepRepTypeHolder ()
  {
  }

  public HepRepTypeHolder (hep.graphics.heprep.corba.idl.HepRepType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hep.graphics.heprep.corba.idl.HepRepTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hep.graphics.heprep.corba.idl.HepRepTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corba.idl.HepRepTypeHelper.type ();
  }

}
