package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepAttDef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Attribute Definition
public final class HepRepAttDef implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String desc = null;
  public String category = null;
  public String extra = null;

  public HepRepAttDef ()
  {
  } // ctor

  public HepRepAttDef (String _name, String _desc, String _category, String _extra)
  {
    name = _name;
    desc = _desc;
    category = _category;
    extra = _extra;
  } // ctor

} // class HepRepAttDef
