package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepTypeTree.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// TypeTree
public final class HepRepTypeTree implements org.omg.CORBA.portable.IDLEntity
{
  public hep.graphics.heprep.corba.idl.HepRepTreeID id = null;
  public hep.graphics.heprep.corba.idl.HepRepType types[] = null;

  public HepRepTypeTree ()
  {
  } // ctor

  public HepRepTypeTree (hep.graphics.heprep.corba.idl.HepRepTreeID _id, hep.graphics.heprep.corba.idl.HepRepType[] _types)
  {
    id = _id;
    types = _types;
  } // ctor

} // class HepRepTypeTree
