package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepTreeID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// TreeID
public final class HepRepTreeID implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String version = null;

  public HepRepTreeID ()
  {
  } // ctor

  public HepRepTreeID (String _name, String _version)
  {
    name = _name;
    version = _version;
  } // ctor

} // class HepRepTreeID
