package hep.graphics.heprep.corba.idl;

/**
* hep/graphics/heprep/corba/idl/HepRepTreeIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// TreeID
public final class HepRepTreeIDHolder implements org.omg.CORBA.portable.Streamable
{
  public hep.graphics.heprep.corba.idl.HepRepTreeID value = null;

  public HepRepTreeIDHolder ()
  {
  }

  public HepRepTreeIDHolder (hep.graphics.heprep.corba.idl.HepRepTreeID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corba.idl.HepRepTreeIDHelper.type ();
  }

}
