package hep.graphics.heprep.corba.idl;

/**
* hep/graphics/heprep/corba/idl/HepRepHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:16 AM PDT
*/


// HepRep
public final class HepRepHolder implements org.omg.CORBA.portable.Streamable
{
  public hep.graphics.heprep.corba.idl.HepRep value = null;

  public HepRepHolder ()
  {
  }

  public HepRepHolder (hep.graphics.heprep.corba.idl.HepRep initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hep.graphics.heprep.corba.idl.HepRepHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hep.graphics.heprep.corba.idl.HepRepHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corba.idl.HepRepHelper.type ();
  }

}
