package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Action
public final class HepRepAction implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String expression = null;

  public HepRepAction ()
  {
  } // ctor

  public HepRepAction (String _name, String _expression)
  {
    name = _name;
    expression = _expression;
  } // ctor

} // class HepRepAction
