package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepAttValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Attribute Value
public final class HepRepAttValue implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public org.omg.CORBA.Any value = null;
  public int showLabel = (int)0;

  public HepRepAttValue ()
  {
  } // ctor

  public HepRepAttValue (String _name, org.omg.CORBA.Any _value, int _showLabel)
  {
    name = _name;
    value = _value;
    showLabel = _showLabel;
  } // ctor

} // class HepRepAttValue
