package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/HepRepType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/


// Type
public final class HepRepType implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String desc = null;
  public String infoURL = null;

  // but that sort of recursion doesn't work.
  public hep.graphics.heprep.corba.idl.HepRepType types[] = null;
  public hep.graphics.heprep.corba.idl.HepRepAttDef attDefs[] = null;
  public hep.graphics.heprep.corba.idl.HepRepAttValue attValues[] = null;

  public HepRepType ()
  {
  } // ctor

  public HepRepType (String _name, String _desc, String _infoURL, hep.graphics.heprep.corba.idl.HepRepType[] _types, hep.graphics.heprep.corba.idl.HepRepAttDef[] _attDefs, hep.graphics.heprep.corba.idl.HepRepAttValue[] _attValues)
  {
    name = _name;
    desc = _desc;
    infoURL = _infoURL;
    types = _types;
    attDefs = _attDefs;
    attValues = _attValues;
  } // ctor

} // class HepRepType
