package hep.graphics.heprep.corba.idl;


/**
* hep/graphics/heprep/corba/idl/StringArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRep.idl
* Tuesday, June 10, 2003 10:19:15 AM PDT
*/

public final class StringArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringArrayHolder ()
  {
  }

  public StringArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hep.graphics.heprep.corba.idl.StringArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hep.graphics.heprep.corba.idl.StringArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corba.idl.StringArrayHelper.type ();
  }

}
