package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepInstance.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// Instance
public abstract class HepRepInstance extends hep.graphics.heprep.corbavalue.idl.HepRepAttribute
{
  public hep.graphics.heprep.corbavalue.idl.HepRepInstance[] instances = null;
  public hep.graphics.heprep.corbavalue.idl.HepRepType typeName = null;
  public hep.graphics.heprep.corbavalue.idl.HepRepPoint[] points = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepInstanceHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.instances = hep.graphics.heprep.corbavalue.idl.HepRepInstanceListHelper.read (istream);
    this.typeName = hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.read (istream);
    this.points = hep.graphics.heprep.corbavalue.idl.HepRepPointListHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    hep.graphics.heprep.corbavalue.idl.HepRepInstanceListHelper.write (ostream, this.instances);
    hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.write (ostream, this.typeName);
    hep.graphics.heprep.corbavalue.idl.HepRepPointListHelper.write (ostream, this.points);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepInstanceHelper.type ();
  }
} // class HepRepInstance
