package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepAttDef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// Attribute Definition
public abstract class HepRepAttDef implements org.omg.CORBA.portable.StreamableValue
{
  public String name = null;
  public String desc = null;
  public String category = null;
  public String extra = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepAttDefHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.name = istream.read_string ();
    this.desc = istream.read_string ();
    this.category = istream.read_string ();
    this.extra = istream.read_string ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.name);
    ostream.write_string (this.desc);
    ostream.write_string (this.category);
    ostream.write_string (this.extra);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepAttDefHelper.type ();
  }
} // class HepRepAttDef
