package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepAttribute.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/

public abstract class HepRepAttribute implements org.omg.CORBA.portable.StreamableValue
{
  public hep.graphics.heprep.corbavalue.idl.HepRepAttValue[] attValues = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepAttributeHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.attValues = hep.graphics.heprep.corbavalue.idl.HepRepAttValueListHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    hep.graphics.heprep.corbavalue.idl.HepRepAttValueListHelper.write (ostream, this.attValues);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepAttributeHelper.type ();
  }
} // class HepRepAttribute
