package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepInstanceTree.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// InstanceTree
public abstract class HepRepInstanceTree extends hep.graphics.heprep.corbavalue.idl.HepRepTreeID
{
  public hep.graphics.heprep.corbavalue.idl.HepRepTreeID typeTreeID = null;
  public hep.graphics.heprep.corbavalue.idl.HepRepTreeID[] instanceTreeIDs = null;
  public hep.graphics.heprep.corbavalue.idl.HepRepInstance[] instances = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepInstanceTreeHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.typeTreeID = hep.graphics.heprep.corbavalue.idl.HepRepTreeIDHelper.read (istream);
    this.instanceTreeIDs = hep.graphics.heprep.corbavalue.idl.HepRepTreeIDListHelper.read (istream);
    this.instances = hep.graphics.heprep.corbavalue.idl.HepRepInstanceListHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    hep.graphics.heprep.corbavalue.idl.HepRepTreeIDHelper.write (ostream, this.typeTreeID);
    hep.graphics.heprep.corbavalue.idl.HepRepTreeIDListHelper.write (ostream, this.instanceTreeIDs);
    hep.graphics.heprep.corbavalue.idl.HepRepInstanceListHelper.write (ostream, this.instances);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepInstanceTreeHelper.type ();
  }
} // class HepRepInstanceTree
