package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// Type
public abstract class HepRepType extends hep.graphics.heprep.corbavalue.idl.HepRepDefinition
{
  public hep.graphics.heprep.corbavalue.idl.HepRepType parent = null;
  public String name = null;
  public String desc = null;
  public String infoURL = null;
  public hep.graphics.heprep.corbavalue.idl.HepRepType[] types = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.parent = hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.read (istream);
    this.name = istream.read_string ();
    this.desc = istream.read_string ();
    this.infoURL = istream.read_string ();
    this.types = hep.graphics.heprep.corbavalue.idl.HepRepTypeListHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.write (ostream, this.parent);
    ostream.write_string (this.name);
    ostream.write_string (this.desc);
    ostream.write_string (this.infoURL);
    hep.graphics.heprep.corbavalue.idl.HepRepTypeListHelper.write (ostream, this.types);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepTypeHelper.type ();
  }
} // class HepRepType
