package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// HepRep
public interface HepRepOperations 
{
  hep.graphics.heprep.corbavalue.idl.HepRepInstanceTree getInstanceTreeTop (String instanceTreeName, String instanceTreeVersion);
  hep.graphics.heprep.corbavalue.idl.HepRepTypeTree getTypeTree (String typeTreeName, String typeTreeVersion);
  hep.graphics.heprep.corbavalue.idl.HepRepInstanceTree getInstances (String instanceTreeName, String instanceTreeVersion, String[] typeNames);
  hep.graphics.heprep.corbavalue.idl.HepRepInstanceTree getInstancesAfterAction (String instanceTreeName, String instanceTreeVersion, String[] typeNames, hep.graphics.heprep.corbavalue.idl.HepRepAction[] actions, boolean getPoints, boolean getDrawAtts, boolean getNonDrawAtts, String[] invertAtts);
  String[] getLayerOrder ();
  String checkForException ();
} // interface HepRepOperations
