package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepDefinition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/

public abstract class HepRepDefinition extends hep.graphics.heprep.corbavalue.idl.HepRepAttribute
{
  public hep.graphics.heprep.corbavalue.idl.HepRepAttDef[] attDefs = null;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepDefinitionHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.attDefs = hep.graphics.heprep.corbavalue.idl.HepRepAttDefListHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    hep.graphics.heprep.corbavalue.idl.HepRepAttDefListHelper.write (ostream, this.attDefs);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepDefinitionHelper.type ();
  }
} // class HepRepDefinition
