package hep.graphics.heprep.corbavalue.idl;


/**
* hep/graphics/heprep/corbavalue/idl/HepRepAttValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from hep/graphics/heprep/HepRepValue.idl
* Tuesday, June 10, 2003 10:19:18 AM PDT
*/


// Attribute Value
public abstract class HepRepAttValue implements org.omg.CORBA.portable.StreamableValue
{
  public String name = null;
  public org.omg.CORBA.Any value = null;
  public int showLabel = (int)0;

  private static String[] _truncatable_ids = {
    hep.graphics.heprep.corbavalue.idl.HepRepAttValueHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.name = istream.read_string ();
    this.value = istream.read_any ();
    this.showLabel = istream.read_long ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.name);
    ostream.write_any (this.value);
    ostream.write_long (this.showLabel);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hep.graphics.heprep.corbavalue.idl.HepRepAttValueHelper.type ();
  }
} // class HepRepAttValue
